// ── Supabase ──────────────────────────────────────────────────────
// Handles all communication with the Supabase database.
// Uses the authenticated user's session token for all requests
// so RLS treats every call as that specific user.
// Tools are pre-generated by extract-schema.js into tools.json.

import { createClient } from "@supabase/supabase-js";
import prebuiltTools from "./tools.json";

// Base client — used for auth operations only
export const supabase = createClient(
  import.meta.env.VITE_SUPABASE_URL,
  import.meta.env.VITE_SUPABASE_ANON_KEY,
);

// ── Authenticated client ──────────────────────────────────────────

export async function getAuthenticatedClient() {
  const {
    data: { session },
  } = await supabase.auth.getSession();

  if (!session) return supabase;

  return createClient(
    import.meta.env.VITE_SUPABASE_URL,
    import.meta.env.VITE_SUPABASE_ANON_KEY,
    {
      global: {
        headers: {
          Authorization: `Bearer ${session.access_token}`,
        },
      },
    },
  );
}

// ── Session user ──────────────────────────────────────────────────

export type SessionUser = {
  id: string;
  email: string | undefined;
  metadata: Record<string, any>;
};

export async function getSessionUser(): Promise<SessionUser | null> {
  const {
    data: { session },
  } = await supabase.auth.getSession();

  if (!session?.user) return null;

  const { user } = session;
  console.log("[IA] session user:", user.id, user.email);
  return {
    id: user.id,
    email: user.email,
    metadata: user.user_metadata ?? {},
  };
}

// ── Tool generation ───────────────────────────────────────────────
// tools.json is the full source of truth.
// At runtime we strip enum values and description strings from field
// properties — Claude already has that detail from the system prompt
// schema lines, so the tool payload only needs type + required.

export type IATool = {
  name: string;
  description: string;
  input_schema: object;
};

function slimProperties(props: Record<string, any>): Record<string, any> {
  const slimmed: Record<string, any> = {};
  for (const [key, def] of Object.entries(props)) {
    // Keep only type, drop enum, description, nullable etc
    slimmed[key] = { type: def.type ?? "string" };
  }
  return slimmed;
}

function slimTool(tool: any): IATool {
  const schema = tool.input_schema as any;
  if (!schema?.properties) return tool;

  const slimSchema = { ...schema, properties: {} as Record<string, any> };

  for (const [key, val] of Object.entries(
    schema.properties as Record<string, any>,
  )) {
    if (val.type === "object" && val.properties) {
      slimSchema.properties[key] = {
        ...val,
        properties: slimProperties(val.properties),
      };
    } else {
      slimSchema.properties[key] = { type: val.type ?? "string" };
    }
  }

  return { ...tool, input_schema: slimSchema };
}

export function buildToolsFromSchema(): IATool[] {
  const tools = prebuiltTools as IATool[];
  const slimmed = tools.map(slimTool);
  console.log("[IA] tools loaded:", slimmed.length);
  return slimmed;
}

export async function executeTool(
  name: string,
  input: Record<string, unknown>,
): Promise<string> {
  const client = await getAuthenticatedClient();

  if (name === "list_tables") {
    return JSON.stringify({ tables: Object.keys(RUNTIME_SCHEMA) });
  }

  const match = name.match(/^(query|create|update|delete)_(.+)$/);
  if (!match) return JSON.stringify({ error: `Unknown tool: ${name}` });

  const [, cmd, tablename] = match;

  switch (cmd) {
    case "query": {
      let query = client.from(tablename).select("*");
      const filters = input.filters as Record<string, unknown> | undefined;
      if (filters) {
        for (const [key, value] of Object.entries(filters)) {
          if (value === "" || value === null || value === undefined) continue;
          query = query.eq(key, value as string);
        }
      }
      const { data, error } = await query;
      if (error) return JSON.stringify({ error: error.message });
      return JSON.stringify({ [tablename]: data });
    }

    case "create": {
      const { data, error } = await client
        .from(tablename)
        .insert(input.data as object)
        .select()
        .single();
      if (error) return JSON.stringify({ error: error.message });
      return JSON.stringify({ [tablename]: data });
    }

    case "update": {
      const { data, error } = await client
        .from(tablename)
        .update(input.data as object)
        .eq("id", input.id as string)
        .select();
      if (error) return JSON.stringify({ error: error.message });
      return JSON.stringify({ [tablename]: data });
    }

    case "delete": {
      const { error } = await client
        .from(tablename)
        .delete()
        .eq("id", input.id as string);
      if (error) return JSON.stringify({ error: error.message });
      return JSON.stringify({ success: true });
    }

    default:
      return JSON.stringify({ error: `Unknown command: ${cmd}` });
  }
}
